name: ecommerce_dbt # dbt project name
version: "1.0.0"

profile: ecommerce_dbt # connection profile in profiles.yml

model-paths: ["models"] # Where will be our SQL models

models:
  ecommerce_dbt:
    staging:
      +materialized: view # Create a view in the DB for staging models

    intermediate:
      +materialized: view # Create a view in the DB for intermediate models

    marts:
      +materialized: table # Create a table in the DB for mart models