"""
Product metrics Gold streaming job.

This job reads valid events from the Silver layer
and produces business metrics aggregated by product.

Metrics produced:
- total_events
- views
- add_to_carts
- purchases
- revenue
- unique_users
- unique_viewers
- unique_buyers
- conversion_rate

Each row in the Gold output corresponds to a product.

The Silver layer serves as the source of truth:
invalid events have already been excluded by the Silver layer.
"""

from pyspark.sql import DataFrame
from pyspark.sql import functions as F
from utils.spark_session import create_spark_session
from schemas.ecommerce_schema import BRONZE_SCHEMA
from config.config import (
    SILVER_PATH,
    GOLD_PATH,
    GOLD_CHECKPOINT_PATH,
    WATERMARK_DELAY
)


# Product metrics gold paths

PRODUCT_GOLD_PATH = f"{GOLD_PATH}/product_metrics"
PRODUCT_GOLD_CHECKPOINT_PATH = f"{GOLD_CHECKPOINT_PATH}/product_metrics"


# Transformation

def build_product_metrics(df: DataFrame) -> DataFrame:
    """
    Computes Gold metrics by product and one-hour window. 

    This function contains only the transformation logic. 
    It can therefore be tested independently of the streaming process. 

    Parameters:
    - df : DataFrame -> DataFrame containing valid Silver events. 
    Returns:
    - DataFrame -> DataFrame containing aggregated product metrics.
    """


    # Watermark

    watermarked_df = (
        df.withWatermark("timestamp", WATERMARK_DELAY)
    )


    # Product metrics
    # The aggregation is performed by product and one-hour event-time window.

    product_metrics_df = (
        watermarked_df
        .groupBy(
            "product_id",
            F.window(
                F.col("timestamp"),
                "1 hour"
            )
        )
        .agg(
            # Total number of events for the product during the window.
            F.count("*").alias("total_events"),

            # Number of product views.
            F.sum(
                F.when(
                    F.col("event_type") == "view",
                    1
                ).otherwise(0)
            ).alias("views"),

            # Number of add-to-cart events.
            F.sum(
                F.when(
                    F.col("event_type") == "add_to_cart",
                    1
                ).otherwise(0)
            ).alias("add_to_carts"),

            # Number of purchases.
            F.sum(
                F.when(
                    F.col("event_type") == "purchase",
                    1
                ).otherwise(0)
            ).alias("purchases"),

            # Total revenue generated by the product.
            F.sum(
                F.when(
                    F.col("event_type") == "purchase",
                    F.col("price")
                ).otherwise(0)
            ).alias("revenue"),

            # Approximate number of unique users who interacted with the product during the window.
            # approx_count_distinct() is used because exact countDistinct() is not supported for this type of streaming aggregation.
            F.approx_count_distinct("user_id").alias("unique_users"),

            # Approximate number of unique users who viewed the product during the window.
            F.approx_count_distinct(
                F.when(
                    F.col("event_type") == "view",
                    F.col("user_id")
                )
            ).alias("unique_viewers"),

            # Approximate number of unique users who purchased the product during the window.
            F.approx_count_distinct(
                F.when(
                    F.col("event_type") == "purchase",
                    F.col("user_id")
                )
            ).alias("unique_buyers")
        )
    )


    # Flatten the window structure

    product_metrics_gold_df = (
        product_metrics_df
        .select(
            "product_id",
            F.col("window.start").alias("window_start"),
            F.col("window.end").alias("window_end"),
            "total_events",
            "views",
            "add_to_carts",
            "purchases",
            "revenue",
            "unique_users",
            "unique_viewers",
            "unique_buyers"
        )
    )


    # Calculate Conversion rate column

    product_metrics_gold_df = (
        product_metrics_gold_df
        .withColumn(
            "conversion_rate",
            F.when(
                F.col("unique_viewers") > 0,
                F.col("unique_buyers") / F.col("unique_viewers")
            ).otherwise(0.0)
        )
    )


    return product_metrics_gold_df


# Streaming job
# -------------------------------------------------------------------

def main():
    """
    Launches the Product Metrics streaming job. 

    This function handles only:
        - Spark Session creation
        - reading from Silver
        - calling the transformation
        - writing to Gold
    """


    # Spark session

    spark = create_spark_session("ecommerce-product-metrics")


    # Read Silver

    silver_df = (
        spark.readStream
        .format("parquet")
        .schema(BRONZE_SCHEMA)
        .load(SILVER_PATH)
    )


    # Application de la transformation métier.

    product_metrics_gold_df = build_product_metrics(silver_df)

    # Write Gold for products

    product_metrics_query = (
        product_metrics_gold_df.writeStream
        .format("parquet")
        .outputMode("append")
        .option("path", PRODUCT_GOLD_PATH)
        .option("checkpointLocation", PRODUCT_GOLD_CHECKPOINT_PATH)
        .start()
    )


    # Keep the streaming query alive

    product_metrics_query.awaitTermination()


# Entry point

if __name__ == "__main__":
    main()