"""
User metrics Gold streaming job.

This job reads valid events from the Silver layer
and produces aggregated business metrics per user.

Metrics produced:
    - total_events
    - views
    - add_to_carts
    - purchases
    - revenue
    - unique_products
    - purchase_rate

Each row in the Gold output corresponds to a user
for a one-hour time window.

The Silver layer serves as the source of truth:
invalid events have already been excluded by the Silver layer.
"""

from pyspark.sql import DataFrame
from pyspark.sql import functions as F

from utils.spark_session import create_spark_session
from schemas.ecommerce_schema import BRONZE_SCHEMA
from config.config import SILVER_PATH, GOLD_PATH, GOLD_CHECKPOINT_PATH


# Product metrics gold paths

USER_GOLD_PATH = f"{GOLD_PATH}/user_metrics"
USER_GOLD_CHECKPOINT_PATH = f"{GOLD_CHECKPOINT_PATH}/user_metrics"


# Transformation

def build_user_metrics(df: DataFrame) -> DataFrame:
    """
    Computes Gold metrics per user and per one-hour window. 
    Parameters:
    - df : DataFrame DataFrame containing valid events from the Silver layer. 
    Returns:
    - DataFrame: DataFrame containing aggregated user metrics.
    """

    # Watermark
    # Watermarking allows Spark to limit the amount of state retained for streaming aggregation.
    # Events that arrive very late may no longer modify a window that Spark already considers closed.
    # This is a state management mechanism, not a data quality rule.

    watermarked_df = (
        df.withWatermark("timestamp", "10 minutes")
    )


    # User metrics
    # Aggregation is performed per user and per one-hour time window.
    # Time-based partitioning enables the use of append mode with Parquet output.

    user_metrics_df = (
        watermarked_df
        .groupBy(
            "user_id",
            F.window(
                F.col("timestamp"),
                "1 hour"
            )
        )
        .agg(
            # Total number of events generated by the user.
            F.count("*").alias("total_events"),

            # Number of product views.
            F.sum(
                F.when(
                    F.col("event_type") == "view",
                    1
                ).otherwise(0)
            ).alias("views"),

            # Number of add-to-cart events.
            F.sum(
                F.when(
                    F.col("event_type") == "add_to_cart",
                    1
                ).otherwise(0)
            ).alias("add_to_carts"),

            # Number of purchases.
            F.sum(
                F.when(
                    F.col("event_type") == "purchase",
                    1
                ).otherwise(0)
            ).alias("purchases"),

            # Total revenue generated by the user.
            F.sum(
                F.when(
                    F.col("event_type") == "purchase",
                    F.col("price")
                ).otherwise(0)
            ).alias("revenue"),

            # Number of different products interacted with by the user.
            # countDistinct() is not used because it is not supported for this type of streaming aggregation.
            F.approx_count_distinct(
                "product_id"
            ).alias("unique_products")
        )
    )

    # Flatten the window structure

    user_metrics_gold_df = (
        user_metrics_df
        .select(
            "user_id",
            F.col("window.start").alias("window_start"),
            F.col("window.end").alias("window_end"),
            "total_events",
            "views",
            "add_to_carts",
            "purchases",
            "revenue",
            "unique_products"
        )
    )

    # Calculate Purchase rate 
    # This metric represents the proportion of the user's events that correspond to purchases during the window.

    user_metrics_gold_df = (
        user_metrics_gold_df
        .withColumn(
            "purchase_rate",
            F.when(
                F.col("total_events") > 0,
                F.col("purchases") / F.col("total_events")
            ).otherwise(0.0)
        )
    )

    return user_metrics_gold_df


# Streaming job

def main():
    """
    Launches the User Metrics streaming job. 

    This function handles only:
    - Spark Session creation
    - reading from Silver
    - calling the transformation
    - writing to Gold
    """

    # Spark session

    spark = create_spark_session("ecommerce-user-metrics")


    # Read Silver

    silver_df = (
        spark.readStream
        .format("parquet")
        .schema(BRONZE_SCHEMA)
        .load(SILVER_PATH)
    )

    # Application of the business transformation.

    user_metrics_gold_df = build_user_metrics(silver_df)


    # Writing Gold metrics in Parquet format.

    user_metrics_query = (
        user_metrics_gold_df.writeStream
        .format("parquet")
        .outputMode("append")
        .option("path", USER_GOLD_PATH)
        .option("checkpointLocation", USER_GOLD_CHECKPOINT_PATH)
        .start()
    )


    # Keep the streaming query alive

    user_metrics_query.awaitTermination()


# Entry point

if __name__ == "__main__":
    main()