"""
User metrics Gold streaming job.

Ce job lit les événements valides depuis la couche Silver
et produit des métriques métier agrégées par utilisateur.

Métriques produites :
    - total_events
    - views
    - add_to_carts
    - purchases
    - revenue
    - unique_products
    - purchase_rate

Chaque ligne de la sortie Gold correspond à un utilisateur
pour une fenêtre temporelle d'une heure.

La couche Silver est utilisée comme source de vérité :
les événements invalides ont déjà été exclus par la couche Silver.
"""

from pyspark.sql import functions as F

from utils.spark_session import create_spark_session
from schemas.ecommerce_schema import BRONZE_SCHEMA


# Spark session

spark = create_spark_session("ecommerce-user-metrics")


# Paths

SILVER_PATH = "/lake/silver"
GOLD_PATH = "/lake/gold/user_metrics"
GOLD_CHECKPOINT = "/lake/checkpoints/gold/user_metrics"


# Read Silver

silver_df = (
    spark.readStream
    .format("parquet")
    .schema(BRONZE_SCHEMA)
    .load(SILVER_PATH)
)


# Watermark
# Watermarking allows Spark to limit the amount of state retained for streaming aggregation.
# Events that arrive very late may no longer modify a window that Spark already considers closed.
# This is a state management mechanism, not a data quality rule.

watermarked_df = (
    silver_df
    .withWatermark("timestamp", "10 minutes")
)


# User metrics
# Aggregation is performed per user and per one-hour time window.
# Time-based partitioning enables the use of append mode with Parquet output.

user_metrics_df = (
    watermarked_df
    .groupBy(
        "user_id",
        F.window(
            F.col("timestamp"),
            "1 hour"
        )
    )
    .agg(
        # Total number of events generated by the user.
        F.count("*").alias("total_events"),

        # Number of product views.
        F.sum(
            F.when(
                F.col("event_type") == "view",
                1
            ).otherwise(0)
        ).alias("views"),

        # Number of add-to-cart events.
        F.sum(
            F.when(
                F.col("event_type") == "add_to_cart",
                1
            ).otherwise(0)
        ).alias("add_to_carts"),

        # Number of purchases.
        F.sum(
            F.when(
                F.col("event_type") == "purchase",
                1
            ).otherwise(0)
        ).alias("purchases"),

        # Total revenue generated by the user.
        F.sum(
            F.when(
                F.col("event_type") == "purchase",
                F.col("price")
            ).otherwise(0)
        ).alias("revenue"),

        # Number of different products interacted with by the user.
        # countDistinct() is not used because it is not supported for this type of streaming aggregation.
        F.approx_count_distinct(
            "product_id"
        ).alias("unique_products")
    )
)


# Flatten the window structure

user_metrics_gold_df = (
    user_metrics_df
    .select(
        "user_id",
        F.col("window.start").alias("window_start"),
        F.col("window.end").alias("window_end"),
        "total_events",
        "views",
        "add_to_carts",
        "purchases",
        "revenue",
        "unique_products"
    )
)


# Calculate Purchase rate 
# This metric represents the proportion of the user's events that correspond to purchases during the window.

user_metrics_gold_df = (
    user_metrics_gold_df
    .withColumn(
        "purchase_rate",
        F.when(
            F.col("total_events") > 0,
            F.col("purchases") / F.col("total_events")
        ).otherwise(0.0)
    )
)


# Write Gold

user_metrics_query = (
    user_metrics_gold_df.writeStream
    .format("parquet")
    .outputMode("append")
    .option("path", GOLD_PATH)
    .option("checkpointLocation", GOLD_CHECKPOINT)
    .start()
)


# Keep the streaming query alive

user_metrics_query.awaitTermination()