from pyspark.sql import DataFrame, SparkSession

from jobs.serving.common.postgres import (
    cleanup_staging,
    upsert_from_staging,
    write_to_staging,
)
from jobs.serving.common.spark import get_spark_session


# PostgreSQL configuration

from config.config import (
    GOLD_PATH,
    GOLD_USER_METRICS_TABLE
)

# Location of the Gold user metrics dataset.
USER_GOLD_PATH = f"{GOLD_PATH}/user_metrics"

# Temporary PostgreSQL table used during publication.
STAGING_TABLE = f"{GOLD_USER_METRICS_TABLE}_staging"


# Serving contract
# Columns exposed by the User Metrics Serving table.

USER_METRICS_COLUMNS = [
    "window_start",
    "window_end",
    "user_id",
    "total_events",
    "views",
    "add_to_carts",
    "purchases",
    "revenue",
    "unique_products",
    "purchase_rate",
]


# Business key identifying one unique user metric record.
# One user can therefore have only one record for a given hourly window in the PostgreSQL Serving table.

USER_METRICS_CONFLICT_COLUMNS = [
    "window_start",
    "window_end",
    "user_id",
]


# Read Gold data

def read_user_metrics(spark: SparkSession) -> DataFrame:
    """
    Read user metrics generated by the Gold layer.
    The Gold dataset is stored as Parquet in the lake.
    """

    return spark.read.parquet(USER_GOLD_PATH)


# Prepare data

def prepare_user_metrics(df: DataFrame) -> DataFrame:
    """
    Select only the columns required by the Serving contract.

    This keeps the publisher independent from any additional
    columns that may be added to the Gold dataset.
    """

    return df.select(*USER_METRICS_COLUMNS)


# Main publication workflow

def main() -> None:
    """
    Publish Gold user metrics into PostgreSQL Serving.
    Workflow: Gold Parquet > Prepare dataset > PostgreSQL staging > UPSERT into Serving > Cleanup staging
    """

    # Create the SparkSession through the shared infrastructure helper.
    spark = get_spark_session(
        "ServingUserMetricsPublisher"
    )

    try:

        # Read user metrics from the Gold layer.
        gold_df = read_user_metrics(spark)

        # Prepare the dataset according to the Serving contract.
        prepared_df = prepare_user_metrics(gold_df)

        # Write the current Gold snapshot to the staging table.
        write_to_staging(
            df=prepared_df,
            staging_table=STAGING_TABLE,
        )

        # Merge staging data into the final Serving table.
        # The shared PostgreSQL helper generates and executes the UPSERT using the business key defined above.
        upsert_from_staging(
            spark=spark,
            staging_table=STAGING_TABLE,
            target_table=GOLD_USER_METRICS_TABLE,
            columns=USER_METRICS_COLUMNS,
            conflict_columns=USER_METRICS_CONFLICT_COLUMNS,
        )

        # Remove the temporary staging table.
        cleanup_staging(
            spark=spark,
            staging_table=STAGING_TABLE,
        )

        print("User metrics successfully published to PostgreSQL.")

    finally:
        # Always stop Spark, including when an exception occurs.
        spark.stop()


if __name__ == "__main__":
    main()