from pyspark.sql import DataFrame, SparkSession
from jobs.serving.common.postgres import (
    cleanup_staging,
    upsert_from_staging,
    write_to_staging,
)
from jobs.serving.common.spark import get_spark_session


# PostgreSQL configuration

from config.config import (
    GOLD_PATH,
    GOLD_PRODUCT_METRICS_TABLE
)
# Location of the Gold product metrics dataset.
PRODUCT_GOLD_PATH = f"{GOLD_PATH}/product_metrics"

# Temporary PostgreSQL table used during publication.
STAGING_TABLE = f"{GOLD_PRODUCT_METRICS_TABLE}_staging"


# Columns exposed by the Product Metrics Serving table.

PRODUCT_METRICS_COLUMNS = [
    "window_start",
    "window_end",
    "product_id",
    "total_events",
    "views",
    "add_to_carts",
    "purchases",
    "revenue",
    "unique_users",
    "unique_viewers",
    "unique_buyers",
    "conversion_rate",
]

# Business key identifying one unique product metric record.
# A product can therefore have only one record for a given time window in the PostgreSQL Serving table.

PRODUCT_METRICS_CONFLICT_COLUMNS = [
    "window_start",
    "window_end",
    "product_id",
]


# Read Gold data

def read_product_metrics(spark: SparkSession) -> DataFrame:
    """
    Read product metrics generated by the Gold layer.
    The Gold dataset is stored as Parquet in the lake.
    """

    return spark.read.parquet(PRODUCT_GOLD_PATH)


# Prepare data

def prepare_product_metrics(df: DataFrame) -> DataFrame:
    """
    Select only the columns required by the PostgreSQL Serving table to prevents unexpected Gold columns 
    from being propagated automatically into the PostgreSQL Serving layer.
    """

    return df.select(*PRODUCT_METRICS_COLUMNS)


# Main publication workflow

def main() -> None:
    """
    Publish Gold product metrics into PostgreSQL Serving.
    """

    # Create the SparkSession through the shared infrastructure
    spark = get_spark_session(
        "ServingProductMetricsPublisher"
    )

    try:

        # Read the Gold dataset.
        gold_df = read_product_metrics(spark)

        # Keep only the Serving contract columns.
        prepared_df = prepare_product_metrics(gold_df)

        # Write the current Gold snapshot to staging.
        write_to_staging(
            df=prepared_df,
            staging_table=STAGING_TABLE,
        )

        # Merge staging into the final Serving table.
        upsert_from_staging(
            spark=spark,
            staging_table=STAGING_TABLE,
            target_table=GOLD_PRODUCT_METRICS_TABLE,
            columns=PRODUCT_METRICS_COLUMNS,
            conflict_columns=PRODUCT_METRICS_CONFLICT_COLUMNS,
        )

        # Remove the temporary staging table.
        cleanup_staging(
            spark=spark,
            staging_table=STAGING_TABLE,
        )

        print("Product metrics successfully published to PostgreSQL.")

    finally:
        # Always stop Spark, including when an exception occurs.
        spark.stop()


# Application entrypoint

if __name__ == "__main__":
    main()